"""Add user_id to resources

Revision ID: 20da4242a8e5
Revises: 092b5752fd0f
Create Date: 2026-08-15 19:12:35.871312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20da4242a8e5'
down_revision: Union[str, Sequence[str], None] = '092b5752fd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hitl_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hitl_items', 'users', ['user_id'], ['id'])
    op.add_column('product_info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_info', 'users', ['user_id'], ['id'])
    op.add_column('workspaces', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'user_id')
    op.drop_constraint(None, 'product_info', type_='foreignkey')
    op.drop_column('product_info', 'user_id')
    op.drop_constraint(None, 'hitl_items', type_='foreignkey')
    op.drop_column('hitl_items', 'user_id')
    # ### end Alembic commands ###
