"""Add HITLItem

Revision ID: 930a8314aae6
Revises: 
Create Date: 2026-08-13 12:20:57.846436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930a8314aae6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hitl_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('attribute_key', sa.String(), nullable=True),
    sa.Column('extracted_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_items_id'), 'hitl_items', ['id'], unique=False)
    op.create_index(op.f('ix_hitl_items_product_name'), 'hitl_items', ['product_name'], unique=False)
    op.create_table('product_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_info_category'), 'product_info', ['category'], unique=False)
    op.create_index(op.f('ix_product_info_id'), 'product_info', ['id'], unique=False)
    op.create_index(op.f('ix_product_info_product_name'), 'product_info', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_product_name'), table_name='product_info')
    op.drop_index(op.f('ix_product_info_id'), table_name='product_info')
    op.drop_index(op.f('ix_product_info_category'), table_name='product_info')
    op.drop_table('product_info')
    op.drop_index(op.f('ix_hitl_items_product_name'), table_name='hitl_items')
    op.drop_index(op.f('ix_hitl_items_id'), table_name='hitl_items')
    op.drop_table('hitl_items')
    # ### end Alembic commands ###
